<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page title_Form 6200</name>
   <tag></tag>
   <elementGuidId>26ad4122-8d73-4cbe-bfa0-41ef8ea965fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wb-cont</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='wb-cont']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>35566be7-1ab6-46f5-b96f-7be45c227c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wb-cont</value>
      <webElementGuid>e16f9b5a-5cbb-47ed-85fb-e60c26d27c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>594597b1-f07f-4cdb-8e15-8dc95e68aca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form 6200 - Import certificate for the Grower Requested Own Use (GROU) program</value>
      <webElementGuid>50835263-2f53-4024-b177-36b5c8c74dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wb-cont&quot;)</value>
      <webElementGuid>6fb9350c-6ea1-4bf5-bd6c-7d3c0bb66a29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='wb-cont']</value>
      <webElementGuid>d8e14418-d063-4e07-bdf8-cd356b0cfd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>a69447b9-5121-443d-bbce-1fc4e8c8647c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'wb-cont' and (text() = 'Form 6200 - Import certificate for the Grower Requested Own Use (GROU) program' or . = 'Form 6200 - Import certificate for the Grower Requested Own Use (GROU) program')]</value>
      <webElementGuid>914f1be6-da7e-4bae-a1cb-ce585163370c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
