<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page title_Form 6012 FR</name>
   <tag></tag>
   <elementGuidId>650dacd8-8ffa-47b6-ac2d-ef91cea3ea38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wb-cont</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='wb-cont']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>be197157-ec3b-4345-9ea8-3669e14c0980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wb-cont</value>
      <webElementGuid>fa8dde41-9c6b-47b8-b399-52a988ae9618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>9aabb655-4a34-4d2d-a33a-4d216353c0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Formulaire 6012 - Demande d’homologation d’un produit sous étiquette privée d’après le produit initial</value>
      <webElementGuid>78e6498c-252a-42ec-9364-754bb7173769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wb-cont&quot;)</value>
      <webElementGuid>5cd3260d-36b5-411a-ab7d-d10daf64e240</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='wb-cont']</value>
      <webElementGuid>2755b049-3550-4f73-abef-e51cb4cafa77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>5da1261f-635f-421c-88cb-28f088445a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'wb-cont' and (text() = 'Formulaire 6012 - Demande d’homologation d’un produit sous étiquette privée d’après le produit initial' or . = 'Formulaire 6012 - Demande d’homologation d’un produit sous étiquette privée d’après le produit initial')]</value>
      <webElementGuid>bd8270cf-fe1b-4e74-a7ed-7770777cc616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
