<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NonClose overlay</name>
   <tag></tag>
   <elementGuidId>e7230837-b059-4806-bf19-770e94dcf306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'NonClose overlay' or . = 'NonClose overlay')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6df59f65-8511-4ac8-adf6-a2d7b36bc2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close overlay</value>
      <webElementGuid>4b050dab-9f6f-49c2-9b98-9cc1801da881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn pull-left btn-primary popup-modal-dismiss</value>
      <webElementGuid>43cf6ad1-3084-4eeb-8cc6-8ec6f9299659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56a78b00-b2f0-4f1f-b61a-ab94d379f9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NonClose overlay</value>
      <webElementGuid>40c7d811-08ba-4534-8a13-6a205dbdccb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle_language_confirmation&quot;)/div[@class=&quot;modal-footer&quot;]/button[@class=&quot;btn pull-left btn-primary popup-modal-dismiss&quot;]</value>
      <webElementGuid>d834e444-1873-4322-b36a-66d832550f5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>ac094a9c-061d-4e37-adf6-8ea349e8b87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='toggle_language_confirmation']/div[2]/button[2]</value>
      <webElementGuid>f8a1c800-86e3-4329-ae7e-fd3357bb5018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>7f8c811a-ec62-4a62-a314-85273c1a752b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Close overlay' and @type = 'button' and (text() = 'NonClose overlay' or . = 'NonClose overlay')]</value>
      <webElementGuid>9eb7d7e2-ed6f-446d-8902-dc87f51c142a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
