<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page title_Form 6110 FR</name>
   <tag></tag>
   <elementGuidId>48190bd3-e90f-40b1-b5be-d791c026706d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wb-cont</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='wb-cont']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>861e686f-58dc-4a15-85b0-734b991b71bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wb-cont</value>
      <webElementGuid>435202ea-a117-4bcc-9cf0-db86b6bd1a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>e1856ea4-765c-4c9a-b77b-44a92a97486e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Formulaire 6110 - Project d’Extension du Profil d’emploi pour Usage limités à la Demande des Utilisateurs (PEPUDU)</value>
      <webElementGuid>5a7e8240-adc6-4c62-bc05-555ab829407a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5ac249b1-0848-4d6c-9603-b6eb2538970a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Formulaire 6110 - Project d’Extension du Profil d’emploi pour Usage limités à la Demande des Utilisateurs (PEPUDU)</value>
      <webElementGuid>67c4fcfb-294f-4e95-bbdf-d3fe1c77e02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wb-cont&quot;)</value>
      <webElementGuid>520d6920-0aa4-4705-9f8a-d914dcf0e9b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='wb-cont']</value>
      <webElementGuid>a49fdeca-fbcc-49f6-90cf-2c67b6f67ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>585e8dc7-b9b1-4296-99f1-b95f57c99c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'wb-cont' and (text() = 'Formulaire 6110 - Project d’Extension du Profil d’emploi pour Usage limités à la Demande des Utilisateurs (PEPUDU)' or . = 'Formulaire 6110 - Project d’Extension du Profil d’emploi pour Usage limités à la Demande des Utilisateurs (PEPUDU)')]</value>
      <webElementGuid>7130fee7-1dd3-4135-80e0-0166e5d6d092</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
