<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page title _Form 6006</name>
   <tag></tag>
   <elementGuidId>3034aafd-00c0-40b1-bffd-d24553bc565a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wb-cont</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='wb-cont']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>9d63433d-44d2-4443-b154-d83da21501ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wb-cont</value>
      <webElementGuid>4fbd2aa9-1fa3-455c-969d-47ba670c8be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>ed2f5859-e6d8-4321-af0c-4cf3e9b18600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Form 6006 - Application for research authorization</value>
      <webElementGuid>044ecd7b-5251-4a10-8037-0482d28be282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d40447ad-a30d-45a2-9177-e4cd9333c228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form 6006 - Application for research authorization</value>
      <webElementGuid>43374328-8d96-4f50-b373-8adbd13662be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wb-cont&quot;)</value>
      <webElementGuid>2fc955ec-2ad8-4117-abe7-b253813dbf6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='wb-cont']</value>
      <webElementGuid>6c8383c7-b8c8-409d-8c82-b445fb53e957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>563639b5-64a9-4706-9a4c-83f45e9c2ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'wb-cont' and (text() = 'Form 6006 - Application for research authorization' or . = 'Form 6006 - Application for research authorization')]</value>
      <webElementGuid>cf976ab8-807f-4022-96ea-0a84de92eee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
