<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page title_eIndex Builder - Build Package</name>
   <tag></tag>
   <elementGuidId>be844e24-2d92-4ba1-8f5b-4a16efa076cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wb-cont</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='wb-cont']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>dbce690d-d749-4409-84c7-28a55d4cf54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wb-cont</value>
      <webElementGuid>040efa52-8fa5-4c83-82ba-c2600da74868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>d6dc2272-1098-489e-a263-3aa070b47415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mrgn-bttm-lg</value>
      <webElementGuid>e31ccd0c-507c-460a-98a4-4a4a3ed86881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>eIndex Builder - Build Package</value>
      <webElementGuid>e1da80ce-f542-4639-859b-0285135b939b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wb-cont&quot;)</value>
      <webElementGuid>972f3901-6b47-406d-a414-5740bdc163f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='wb-cont']</value>
      <webElementGuid>19ec7731-aa87-4851-a73f-56611f067982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>12739ecb-ec3f-4619-a2ce-e20bd63806dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'wb-cont' and (text() = 'eIndex Builder - Build Package' or . = 'eIndex Builder - Build Package')]</value>
      <webElementGuid>7e336819-3ac3-4b6d-9b4d-4913cab4414c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
