<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NoClose overlay</name>
   <tag></tag>
   <elementGuidId>71a938d3-3a89-40ac-ac08-7f2f64ce05d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'NoClose overlay' or . = 'NoClose overlay')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea6ca4ee-0d2d-481b-8ae3-6ba2086ad419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close overlay</value>
      <webElementGuid>77862563-f6b7-43b8-9c6a-3e8b56a59369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn pull-left btn-primary popup-modal-dismiss</value>
      <webElementGuid>9b9bf021-bcab-433d-97eb-f2968308bca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96923a97-0544-4921-b9a5-0a52b3cbffa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NoClose overlay</value>
      <webElementGuid>c6b6913f-8b40-4e4b-9df8-ca8f99e7560d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle_language_confirmation&quot;)/div[@class=&quot;modal-footer&quot;]/button[@class=&quot;btn pull-left btn-primary popup-modal-dismiss&quot;]</value>
      <webElementGuid>bc79953e-7a64-41e4-a1c5-c059f157da73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>4dc29b88-1470-453a-9033-e0fe1a027828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='toggle_language_confirmation']/div[2]/button[2]</value>
      <webElementGuid>cb6043b1-f802-4a68-91c0-736562405268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>3e24f999-5cb0-4bb5-88ac-c2eb3db88de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Close overlay' and @type = 'button' and (text() = 'NoClose overlay' or . = 'NoClose overlay')]</value>
      <webElementGuid>4e229e34-d440-4047-a9cf-3ec1d6383fb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
