<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page title_Form 6026 FR</name>
   <tag></tag>
   <elementGuidId>ecdf6860-bf2e-4394-baf9-f3a5636691eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wb-cont</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='wb-cont']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>2e175fef-6a73-408d-9db0-bde9f55772b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wb-cont</value>
      <webElementGuid>4716d9f3-177d-44db-bb93-1dace1165706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>4af351db-d9a4-4bc2-8353-56e6fd3196d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Formulaire 6026 - Changements administratifs à apporter aux renseignements sur la personne-ressource pour les produits antiparasitaires homologués</value>
      <webElementGuid>3b34f08f-e5fe-4a58-8071-b8dfa60b1763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>67b80936-e3a0-4213-b176-d1f015bb8efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Formulaire 6026 - Changements administratifs à apporter aux renseignements sur la personne-ressource pour les produits antiparasitaires homologués</value>
      <webElementGuid>87ede3fa-1566-4b16-a083-974e1ed980a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wb-cont&quot;)</value>
      <webElementGuid>8a8141cc-32d2-483c-a36f-1c5e0f553adb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='wb-cont']</value>
      <webElementGuid>2fb1f625-2a2d-4037-bb10-c2ed7cfaf747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>c45c2ea5-ac3a-4e41-aa01-60059ec8141a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'wb-cont' and (text() = 'Formulaire 6026 - Changements administratifs à apporter aux renseignements sur la personne-ressource pour les produits antiparasitaires homologués' or . = 'Formulaire 6026 - Changements administratifs à apporter aux renseignements sur la personne-ressource pour les produits antiparasitaires homologués')]</value>
      <webElementGuid>bdf660d1-5c23-4c15-8ec5-536165dea19a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
