<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page title_Forms for registrants and applicants</name>
   <tag></tag>
   <elementGuidId>ec18b3f3-d4f4-48a7-8c88-c0ef0c50bdbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wb-cont</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='wb-cont']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>db4c837b-0960-4f95-9880-6342dd66ed7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wb-cont</value>
      <webElementGuid>41b1c8c5-6e75-4a74-96d4-d863a013e3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>property</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>a8a010c1-176d-493a-badc-60a144a7809a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2618e434-50e8-4bd1-9d8c-ccd4fcc15553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forms for registrants and applicants</value>
      <webElementGuid>ae21d695-ec32-4a82-8edd-d63d3446f092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wb-cont&quot;)</value>
      <webElementGuid>c3f5a20c-9c46-4aff-8852-815017123ed1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='wb-cont']</value>
      <webElementGuid>22cb514c-ca99-4e4e-8035-63b8c5eb3725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>ab6d40d8-533d-4c4c-9797-e2fa77b5dbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'wb-cont' and (text() = 'Forms for registrants and applicants' or . = 'Forms for registrants and applicants')]</value>
      <webElementGuid>74091ab0-8df8-4865-b5f0-20d6b62ab60d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
